### ISSUE TITLE
Enhancement Request: Keep original modified dates on directories

### ISSUE THREAD

**Issue by akrabu** [Dr-Emann/applesauce#14]
It would be nice if you could maintain the original access and modified dates.  Just a thought.  Thanks!

**Comment by Dr-Emann** [comment]
Applesauce _does_ reapply the original access and modified dates. MacOS does also keep a "change" date (the last metadata change) which appears to be impossible to set, however.

**Comment by akrabu** [comment]
Weird. Trying to reproduce today (v0.3.0) it maintained the modified date.  Previously, on a large recursive job, the modified date was updated to compression time.  I can't seem to do it on individual files though.  I'll play around and see if I can't reproduce it on a larger dataset.

**Comment by akrabu** [comment]
Ah.  It's folders.  The folder modification dates change, not the files.  Which, I suppose is to be expected.  I just have some picky users that rely on modification dates more than they should to find things haha

**Comment by Dr-Emann** [comment]
@akrabu Believe this should be fixed, in 0.5.2 we should now reset the modified times on directories after we compress their contents. Note that it's not atomic (if you kill applesauce in the middle of an operation, directories won't be reset, and during the compression operation, the directory modified dates will change, then be reset)

**Comment by Dr-Emann** [comment]
With 0.5.3, should also restore timestamps for when the file was created and added as well.
