### ISSUE TITLE
Homebrew installation?

### ISSUE THREAD

**Issue by ylluminate** [Dr-Emann/applesauce#44]
Could you please provide a Homebrew recipe installation method for this/ Your tool looks useful, but it would be considerably more accessible if it had this method available for installation.

**Comment by akrabu** [comment]
Came here all excited because I saw the release email, but it's still not working for me in either 0.4.4, 0.4.5, or 0.4.6 - but I think Dr-Emann's working on it!

**Comment by Dr-Emann** [comment]
Yep, took some.. Trial and error, but it works now! All future releases will automatically be published to that brew tap
