### ISSUE TITLE
Compression file size limit

### ISSUE THREAD

**Issue by tumdum** [Dr-Emann/applesauce#70]
Is the compression file size limit:

https://github.com/Dr-Emann/applesauce/blob/bb7c86cb80c4ccdc796c5f5dbaf83bb25b57f584/crates/applesauce/src/info.rs#L129-L133

something required by the apfs api/design? Or is only a limitation of the current implementation of `applesauce` and could be removed in future?

**Comment by Dr-Emann** [comment]
It's a limitation on apple's side: https://github.com/RJVB/afsctool/issues/17#issuecomment-1296522656

The format itself is limited to 4 GiB of _compressed_ data, but apple's implementation leads to kernel panics on compressed files which are over 4 GiB of data **before compression**.

**Comment by tumdum** [comment]
Thanks for a quick answer! :)
